# Generated by Django 5.0.2 on 2024-02-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_meeting_date_created_alter_meeting_organizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='medication_dosage',
        ),
    ]
