# Generated by Django 5.0.2 on 2024-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_medication_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medication_dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
