# Generated by Django 5.0.2 on 2024-02-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_medication_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='certification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='cpr_certification',
            field=models.ImageField(blank=True, null=True, upload_to='cpr_certs/'),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='first_aid_certification',
            field=models.ImageField(blank=True, null=True, upload_to='fa_certs/'),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
