import 'package:lifeline/core/constant/assets_location.dart';

class EmergencyAidModel {
  String name;
  String image;
  String description;
  EmergencyAidModel({
    required this.name,
    required this.image,
    required this.description,
  });

  static List<EmergencyAidModel> getEmergencyList = [
    EmergencyAidModel(
      name: 'Artificial respiratory',
      image: Assets.image2,
      description:
          'Artificial respiration, also known as rescue breathing, is a technique used to provide oxygen to a person who is not breathing or is experiencing difficulty breathing. It is a crucial skill in basic first aid and cardiopulmonary resuscitation (CPR). Here\'s a step-by-step guide on how to perform artificial respiration: \n Note: Before initiating any rescue efforts, ensure that the scene is safe for both you and the victim. If the person is unresponsive and not breathing normally, it\'s important to activate emergency medical services (call 911 or your local emergency number) before starting artificial respiration.'
          'Note: Before initiating any rescue efforts, ensure that the scene is safe for both you and the victim. If the person is unresponsive and not breathing normally, it\'s important to activate emergency medical services (call 911 or your local emergency number) before starting artificial respiration'
          'Position the Person: Place the person on a firm surface. Ensure their aireir backway is clear of any obstructions, and the head is tilted back slightly to open the airway. Check for Breathing:Lean down close to the person\'s face.Look, listen, and feel for signs of breathing for about 5-10 seconds. If the person is not breathing or is breathing irregularly, artificial respiration is needed. Seal the Person\'s Nose: Pinch the person\'s nostrils closed with your fingers to prevent air from escaping. Create a Seal with Your Mouth: Open your mouth wide and create a seal over the person\'s mouth. Deliver Rescue Breaths: Give two rescue breaths. Each breath should last about 1 to 1.5 seconds. Watch for the chest to rise with each breath. Chest Compression (if trained): If you are trained in CPR and the person still does not have a pulse, combine artificial respiration with chest compressions. Perform 30 chest compressions followed by two rescue breaths. Continue the Cycle: Repeat the cycle of 30 chest compressions and two rescue breaths until emergency medical help arrives or the person starts breathing on their own. \n Tips: Ensure a good seal over the person\'s mouth to maximize the effectiveness of rescue breaths. Do not overinflate the person\'s lungs; allow for passive exhalation. If the chest does not rise, reposition the head and try again. Monitor the person\'s responsiveness and breathing continuously.',
    ),
    EmergencyAidModel(
      name: 'Burns',
      image: Assets.image2,
      description:
          'Burns are injuries caused by heat, chemicals, electricity, or radiation. The severity of a burn depends on the depth, size, and location of the injury. It\'s crucial to know how to administer proper first aid to minimize damage and potential complications. \nTypes of Burns: \nFirst-degree: \nAffects the top layer of skin (epidermis), causing redness, pain, and mild swelling. \nSecond-degree: Involves deeper layers of skin, forming blisters and causing intense pain. \nThird-degree: Destroys deeper tissues, appearing white or charred and causing numbness. \nFourth-degree: Affects underlying muscles and bone, requiring immediate medical attention. \nFirst-Aid Steps: \n 1. Stop the Burning: Remove the person from the heat source and extinguish any flames. For chemical burns, remove contaminated clothing and flush the area with cool water for at least 20 minutes. \n 2. Cool the Burn: Run cool (not cold) water over the burn for 10-20 minutes. Avoid using ice, butter, or greasy substances, which can worsen the injury. \n 3. Cover the Burn: Loosely cover the burn with a sterile bandage or clean cloth to prevent infection. Don\'t burst blisters. \n 4. Elevate the Burn: If possible, elevate the burned area above the heart to reduce swelling. \n 5. Manage Pain: Give over-the-counter pain relievers like ibuprofen or acetaminophen according to the recommended dosage. \n 6. Seek Medical Attention: \n For all third-degree burns, chemical burns larger than a hand, or electrical burns. \n For second-degree burns larger than 3 inches in diameter or on the face, hands, feet, or genitals. \n If the burn is deep, has white or charred appearance, or causes difficulty breathing or vision changes. \n Prevention Tips: \n 1. Use oven mitts, pot holders, and other protective gear while cooking. \n 2. Keep hot liquids and appliances out of reach of children. \n 3. Wear sunscreen with SPF 30 or higher to prevent sunburn. \n 4. Use caution around flammable materials and electrical wires. \n 5. Have a fire extinguisher readily available and know how to use it. \  Additional Tips: \n 1. Stay calm and reassure the injured person. \n 2. Call emergency services immediately if the burn is severe or involves difficulty breathing, confusion, or loss of consciousness. \n 3. Don\'t apply any ointments or medications unless instructed by a medical professional. \n 4. Monitor the burn for signs of infection, such as redness, swelling, pus, or fever. \n 5. Follow-up with a doctor for proper wound care and treatment instructions. \n 6. Remember: This information is for general knowledge only and cannot replace professional medical advice. In case of a burn, always seek medical attention if needed.',
    ),
    EmergencyAidModel(
        name: 'Alergic reaction',
        image: Assets.image3,
        description:
            'An allergic reaction occurs when the body\'s immune system overreacts to a harmless substance, like food, insect stings, or medication. Symptoms can range from mild (hives, itching) to severe and life-threatening (anaphylaxis). Knowing how to recognize and respond to allergic reactions is crucial. \n Types of Allergic Reactions: \n Mild: Skin reactions (hives, redness, itching), watery eyes, sneezing, mild wheezing. \n Moderate: Swelling of lips, tongue, or face, abdominal cramps, nausea, vomiting, difficulty breathing. \n Severe (anaphylaxis): Sudden drop in blood pressure, wheezing, trouble breathing, rapid heartbeat, confusion, shock, unconsciousness. First-Aid Steps: \n 1. Identify the Allergen: If possible, remove the person from the source of the allergen. \n 2. Call Emergency Services Immediately: \n For any signs of anaphylaxis, including difficulty breathing, wheezing, swelling of the throat or tongue, confusion, or loss of consciousness. \n For severe allergic reactions even without anaphylaxis symptoms, especially if they worsen quickly. \n 3. Administer Epinephrine (if available): \n If the person has a known severe allergy and carries an epinephrine auto-injector (e.g., EpiPen), help them use it according to the package instructions. \n Do not wait for symptoms to worsen before using epinephrine. \n 4. Monitor the Person: \n Stay calm and reassure them. \n Loosen tight clothing and elevate the head and shoulders if they have trouble breathing. \n Do not give them anything to eat or drink by mouth. \n Monitor their breathing and pulse rate until help arrives. \n 5. Follow Medical Instructions: \n After a severe reaction, follow all medical advice and attend follow-up appointments.\n Prevention Tips: \n Identify and avoid allergens: Know your triggers and carry an allergy alert bracelet or card. \n Read food labels carefully: Be aware of hidden allergens in ingredients.\n Carry an epinephrine auto-injector: If prescribed, always have it with you and know how to use it.\n Talk to your doctor: Discuss allergy management strategies and emergency plans.\n Teach others about your allergies: Inform family, friends, and caregivers about your allergies and emergency procedures. \n Additional Tips: \n Antihistamines like Benadryl may help with mild symptoms, but never replace epinephrine in case of severe reactions. \n Be aware of delayed reactions, which can occur hours after exposure. \n Educate yourself and others about anaphylaxis and its signs and symptoms. \n Remember: This information is for general knowledge only and cannot replace professional medical advice. Always consult a healthcare professional for specific recommendations and in case of emergencies.'),
    EmergencyAidModel(
      name: 'Fracture and sprains',
      image: Assets.image8,
      description:
          'Differentiating between fractures and sprains can be tricky, but knowing how to administer first aid for both is crucial. While sprains involve stretched or torn ligaments, fractures are broken bones. Recognizing the signs and taking immediate action can minimize pain, swelling, and potential complications. \n Signs and Symptoms: \n Fracture: \n Sudden, sharp pain: Localized or radiating pain at the injury site. \n Deformity: Bone appears bent, twisted, or out of place. \n Swelling and bruising around the area. \n Inability to move or bear weight on the injured limb. \n Crackling or popping sound at the time of injury (not always present). \n Sprain:\n Sharp pain at the joint, usually localized.\n Swelling, bruising, and tenderness around the joint.\n Difficulty moving the joint through its full range of motion.\n Joint feels loose or unstable. \n First Aid Steps:\n 1. Stop the Activity: Immediately cease any movement that could aggravate the injury.\n 2. Apply RICE:\n Rest: Elevate and immobilize the injured limb to prevent further movement.\n Ice: Apply an ice pack wrapped in a cloth for 15-20 minutes at a time, several times a day, to reduce swelling and pain.\n Compression: Wrap the area gently but firmly with an elastic bandage to provide support and reduce swelling.\n Elevation: Raise the injured area above the heart to reduce swelling.\n 3. Seek Medical Attention:\n For any suspected fracture, especially if accompanied by deformity, severe pain, or numbness.\n For sprains that don\'t improve significantly within a few days, especially if pain worsens or swelling persists.\n If the injury involves a joint, bone protruding through the skin (open fracture), or difficulty breathing or moving. \n Prevention Tips:\n Maintain good bone health: Eat calcium-rich foods, get enough vitamin D, and exercise regularly.\n Warm up before physical activity: Stretch and prepare your muscles to prevent strains.\n Wear appropriate footwear: Choose shoes that provide good support and traction.\n Be mindful of your surroundings: Avoid tripping hazards and falls.\n Strengthen your muscles: Regular exercise can improve balance and stability, reducing the risk of sprains and falls. \n Additional Tips:\n Do not attempt to realign a broken bone or dislocated joint.\n Do not apply heat to an injury in the first 24-48 hours.\n Monitor the injury for signs of infection, such as redness, increased pain, or pus.\n Follow medical instructions carefully for proper healing and rehabilitation\n Remember: This information is for general knowledge only and cannot replace professional medical advice. In case of suspected fracture or sprain, always seek medical attention for proper diagnosis and treatment.',
    ),
    EmergencyAidModel(
      name: 'Wound Management',
      image: Assets.image1,
      description:
          'Wounds, whether minor cuts or serious lacerations, are a common occurrence in everyday life. Knowing how to properly manage them is crucial to prevent infection and promote healing. \n Types of Wounds: \n Abrasions: Scrapes that remove the top layer of skin (epidermis). \nLacerations: Cuts that tear deeper into the skin. \nPunctures: Deep, narrow wounds caused by sharp objects. \nAvulsions: Skin torn away from underlying tissue. \nFirst Aid Steps: \n1. Stop the Bleeding: \nApply direct pressure to the wound with a clean cloth or sterile dressing. \nElevate the wound above the heart if possible. \nHold pressure for at least 5-10 minutes, applying more pressure if bleeding persists. \n2. Clean the Wound: \nWash hands thoroughly with soap and water. \nGently rinse the wound with clean, running water or sterile saline solution. \nRemove any visible dirt or debris (avoid tweezers unless necessary). \nPat the wound dry with a clean cloth. \n3. Prevent Infection: \nApply a thin layer of antibiotic ointment if available. \nCover the wound with a sterile dressing or bandage. \n4. Monitor the Wound: \nWatch for signs of infection, such as redness, swelling, pus, or fever. \nChange the dressing daily or as needed. \n5. Seek Medical Attention: \nFor deep wounds, punctures, or wounds near joints or sensitive areas. \nFor wounds that won\'t stop bleeding or show signs of infection. \nFor wounds caused by animal bites or rusty objects. \nPrevention Tips: \nBe cautious in activities that carry risks of cuts or scrapes. \nWear protective clothing and gear when needed (gloves, goggles, etc.). \nKeep tetanus vaccination up-to-date. \nProperly dispose of sharp objects after use. \nAdditional Tips: \nDo not use alcohol, hydrogen peroxide, or iodine on wounds, as they can irritate tissues. \nAvoid touching the wound with your fingers to prevent infection. \nDo not burst blisters, as they protect the wound from further damage. \nElevate the injured area for several days to reduce swelling. \nPain relievers like ibuprofen or acetaminophen can help manage discomfort. \nRemember: This information is for general knowledge only and cannot replace professional medical advice. In case of serious wounds or concerns, always seek medical attention for proper diagnosis and treatment.',
    ),
    EmergencyAidModel(
        name: 'Choking',
        image: Assets.image12,
        description:
            'Choking is a serious medical emergency that occurs when an object blocks the airway, preventing someone from breathing. Recognizing the signs and knowing how to administer first aid promptly can save a life.\nSigns of Choking:\nInability to speak, cough, or breathe effectively.\nClutching the throat with hands.\nRapid, shallow breaths or gasping.\nBluish skin color (cyanosis).\nLoss of consciousness.\nFirst Aid Steps for Adults:\n1. Encourage them to cough: If the person is coughing forcefully, encourage them to continue. Do not interfere.\n2. Back blows: If coughing doesn\'t dislodge the object, stand behind the person and lean them slightly forward. Deliver five firm blows with the heel of your hand between the shoulder blades.\n3. Abdominal thrusts (Heimlich maneuver): If back blows fail, make a fist and place it just above the person\'s navel, thumb side facing their body. Encircle their waist with your other hand and make five quick, upward thrusts. Repeat the cycle of back blows and abdominal thrusts until the object dislodges or they lose consciousness.\n4. Call for help: If the object doesn\'t come out after several cycles or the person loses consciousness, immediately call emergency services and continue with first aid until help arrives.\nFirst Aid Steps for Children and Infants:\n1. Back blows: For infants under one year, lay them face down on your forearm with their head lower than their body. Support their head and jaw with your hand. Deliver five firm blows between the shoulder blades with the heel of your hand.\n2. Chest thrusts: For children over one year and infants who are unresponsive, turn them face up on a firm surface. Place two fingers in the center of their chest, just below the nipple line, and deliver five quick, downward compressions. Repeat the cycle of back blows and chest thrusts until the object comes out or they lose consciousness.\n3. Call for help: If the object doesn\'t come out after several cycles or the child loses consciousness, immediately call emergency services and continue with first aid until help arrives.\nPrevention Tips:\nSupervise children closely while eating, especially those with small objects.\nCut food into small pieces for young children.\nAvoid giving young children hard candies, nuts, popcorn, and other choking hazards.\nBe mindful of food allergies and sensitivities.\nLearn first-aid techniques for choking, including practice on a mannequin.\nAdditional Tips:\nDo not perform the Heimlich maneuver on yourself unless you are completely alone.\nModify first-aid techniques for pregnant women as needed.\nConsider keeping a first-aid kit readily available, including choking relief tools like a back-blow device.\nRemember: This information is for general knowledge only and cannot replace professional medical advice. In case of a choking emergency, always call emergency services immediately and prioritize seeking medical attention.\n'),
    EmergencyAidModel(
      name: 'Basic bleeding control',
      image: Assets.image11,
      description:
          'Bleeding is a common injury, from minor cuts to serious wounds. Knowing how to perform basic bleeding control can minimize blood loss and prevent complications. Here\'s what you need to know:\nTypes of Bleeding:\nArterial: Bright red blood pulsating forcefully indicates serious bleeding requiring immediate medical attention.\nVenous: Dark red blood flowing steadily is less urgent but still needs proper care.\nCapillary: Oozing of small amounts of blood from minor cuts or scrapes.\nFirst Aid Steps:\n1. Assess the scene: Ensure your safety and the safety of the injured person before approaching. Identify the source and severity of the bleeding.\n2. Direct Pressure: Apply firm, continuous pressure directly on the wound with a clean cloth, gauze, or any available material. Do not remove soaked material; add more layers on top.\n3. Elevation: If possible, elevate the bleeding limb above the heart to reduce blood flow.\n4. Pressure Points: For arterial bleeding, apply pressure to specific pressure points between the bleeding wound and the heart to slow blood flow. Learn and use these points with caution and only if direct pressure fails.\n5. Tourniquet (Last resort): Use a tourniquet only as a last resort for severe arterial bleeding that cannot be controlled with direct pressure. Apply it above the wound, tighten until bleeding stops, and secure it in place. Note the time of application and seek immediate medical attention.\n6. Call for Help: Don\'t delay! Call emergency services for any serious bleeding or if unsure about the severity.\nPreventative Tips:\nBe aware of your surroundings and potential hazards.\nWear protective gear during activities that carry risks of cuts or wounds.\nTeach basic first aid to those around you.\nKeep a first-aid kit readily available.\nAdditional Tips:\nDo not remove objects embedded in wounds.\nDo not apply anything but clean material to the wound.\nStay calm and reassure the injured person.\nMonitor the person for signs of shock (confusion, rapid breathing, pale skin).\nRemember: This information is for general knowledge only and cannot replace professional medical advice. In case of serious bleeding, always call emergency services and seek professional medical attention.\n',
    ),
    EmergencyAidModel(
      name: 'Poisoning',
      image: Assets.image9,
      description:
          'Poisoning can occur through any way a harmful substance enters the body, whether it\'s ingested, inhaled, absorbed through skin, or injected. Recognizing the signs quickly and knowing how to respond appropriately can be lifesaving.\nTypes of Poisoning:\nFood poisoning: Caused by contaminated food or water.\nMedication poisoning: Taking too much or the wrong medication.\nHousehold product poisoning: Accidental ingestion of cleaning products, chemicals, or plants.\nAnimal bites and stings: Venom from insects, spiders, or animals can be poisonous.\nCarbon monoxide poisoning: Caused by inhaling fumes from gas appliances or faulty vehicles.\nSigns and Symptoms:\nNausea, vomiting, and diarrhea\nStomach pain and cramps\nDifficulty breathing or wheezing\nConfusion, dizziness, or drowsiness\nSeizures or loss of consciousness\nBurning or irritation in the mouth, throat, or skin\nImportant Note: It\'s crucial to NEVER attempt to diagnose or treat poisoning yourself. Always call emergency services immediately, regardless of the severity of symptoms.\nFirst Aid Steps (While Waiting for Help):\nStay Calm and Assess the Situation: Avoid panicking and ensure your own safety. If possible, identify the poison and the amount ingested/inhaled.\nCall Emergency Services Immediately: Provide them with all available information about the poison, the amount consumed, and the person\'s symptoms.\nKeep the Person Stable and Calm: Do not move them unless they are in immediate danger. Monitor their breathing and alertness.\nDo NOT Induce Vomiting Unless Instructed: This can worsen the situation and cause aspiration.\nDo NOT Give Anything to Eat or Drink: This can interact with the poison or interfere with medical treatment.\nRemove Contaminated Clothing or Jewelry: For skin contact, flush the area with cool water for 15-20 minutes.\nPreserve the Poison Container/Source: This will help medical professionals identify the poison and provide proper treatment.\nPrevention Tips:\nStore harmful substances securely, out of reach of children and pets.\nUse medications exactly as directed and avoid mixing them without consulting a doctor.\nRead labels carefully on household products and use them according to instructions.\nSupervise children closely around potentially hazardous substances.\nInstall carbon monoxide detectors in your home.\nLearn about common poisons and their symptoms.\nAdditional Tips:\nStay informed about poison control centers and their emergency numbers.\nConsider keeping a first-aid kit containing activated charcoal (only use if specifically instructed by medical professionals).\nEducate others about safe storage and handling of potentially poisonous substances.\nRemember: This information is intended for general knowledge only and cannot replace professional medical advice. In case of suspected poisoning, always prioritize seeking immediate medical attention and follow the instructions of emergency services.\n',
    ),
  ];
}
